### ISSUE TITLE
Fix OSError

### ISSUE THREAD

**Issue by sighmon** [ACMILabs/playlist-label#7]
```bash
18.09.19 10:12:58 (+1000)  playlistlabel  Exception in thread Thread-1:
18.09.19 10:12:58 (+1000)  playlistlabel  Traceback (most recent call last):
18.09.19 10:12:58 (+1000)  playlistlabel    File "/usr/local/lib/python3.7/site-packages/amqp/transport.py", line 137, in _connect
18.09.19 10:12:58 (+1000)  playlistlabel      host, port, family, socket.SOCK_STREAM, SOL_TCP)
18.09.19 10:12:58 (+1000)  playlistlabel    File "/usr/local/lib/python3.7/socket.py", line 748, in getaddrinfo
18.09.19 10:12:58 (+1000)  playlistlabel      for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
18.09.19 10:12:58 (+1000)  playlistlabel  socket.gaierror: [Errno -2] Name or service not known
18.09.19 10:12:58 (+1000)  playlistlabel  
18.09.19 10:12:58 (+1000)  playlistlabel  During handling of the above exception, another exception occurred:
18.09.19 10:12:58 (+1000)  playlistlabel  
18.09.19 10:12:58 (+1000)  playlistlabel  Traceback (most recent call last):
18.09.19 10:12:58 (+1000)  playlistlabel    File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
18.09.19 10:12:58 (+1000)  playlistlabel      self.run()
18.09.19 10:12:58 (+1000)  playlistlabel    File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/threading.py", line 53, in run
18.09.19 10:12:58 (+1000)  playlistlabel      reraise(*_capture_exception())
18.09.19 10:12:58 (+1000)  playlistlabel    File "/usr/local/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 54, in reraise
18.09.19 10:12:58 (+1000)  playlistlabel      raise value
18.09.19 10:12:58 (+1000)  playlistlabel    File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/threading.py", line 51, in run
18.09.19 10:12:58 (+1000)  playlistlabel      return old_run(*a, **kw)
18.09.19 10:12:58 (+1000)  playlistlabel    File "/usr/local/lib/python3.7/threading.py", line 865, in run
18.09.19 10:12:58 (+1000)  playlistlabel      self._target(*self._args, **self._kwargs)
18.09.19 10:12:58 (+1000)  playlistlabel    File "app/main.py", line 129, in get_events
18.09.19 10:12:58 (+1000)  playlistlabel      conn.drain_events(timeout=2)
18.09.19 10:12:58 (+1000)  playlistlabel    File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 315, in drain_events
18.09.19 10:12:58 (+1000)  playlistlabel      return self.transport.drain_events(self.connection, **kwargs)
18.09.19 10:12:58 (+1000)  playlistlabel    File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 823, in connection
18.09.19 10:12:58 (+1000)  playlistlabel      self._connection = self._establish_connection()
18.09.19 10:12:58 (+1000)  playlistlabel    File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 778, in _establish_connection
18.09.19 10:12:58 (+1000)  playlistlabel      conn = self.transport.establish_connection()
18.09.19 10:12:58 (+1000)  playlistlabel    File "/usr/local/lib/python3.7/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
18.09.19 10:12:58 (+1000)  playlistlabel      conn.connect()
18.09.19 10:12:58 (+1000)  playlistlabel    File "/usr/local/lib/python3.7/site-packages/amqp/connection.py", line 307, in connect
18.09.19 10:12:58 (+1000)  playlistlabel      self.transport.connect()
18.09.19 10:12:58 (+1000)  playlistlabel    File "/usr/local/lib/python3.7/site-packages/amqp/transport.py", line 77, in connect
18.09.19 10:12:58 (+1000)  playlistlabel      self._connect(self.host, self.port, self.connect_timeout)
18.09.19 10:12:58 (+1000)  playlistlabel    File "/usr/local/lib/python3.7/site-packages/amqp/transport.py", line 148, in _connect
18.09.19 10:12:58 (+1000)  playlistlabel      "failed to resolve broker hostname"))
18.09.19 10:12:58 (+1000)  playlistlabel  OSError: failed to resolve broker hostname
```

**Comment by framigni** [comment]
@sighmon this ticket is very old and, if we haven't done anything about in more than a year, I feel we should just close it

**Comment by sighmon** [comment]
@framigni I still think we should leave it open - this could cause the Playlist Labels to stop updating, so we'll want to get to it at some point.
